name: Node.js CI

on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and lint
        run: |
          npm install
          npm run eslint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          # Node.js 14 has npm 6, so we need to update to the latest.
          npm install -g npm
          npm install
          npm run test
        env:
          CI: true
